#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null

echo ""
echo "=== kernel audit rootfs ==="
uname -a
echo "==========================="
echo ""

exec /bin/sh
